name = "d1-blog-backend"
main = "app/index.ts"
compatibility_date = "2024-03-14"
node_compat = true
minify = true

[[d1_databases]]
binding = "DB"
database_name = "d1-blog"
database_id ="26ddf958-be07-4a73-a733-0332166d216e"

[env.local]
d1_databases=[
  {binding = "DB",database_name = "test-db",database_id ="test-db"}
]
